# Splunk Universal Forwarder — outputs.conf
# Host: Windows 11 Home (Victim) — 192.168.1.188
# Purpose: tell the forwarder where to send collected data
#
# Location on host: %SPLUNK_UF_HOME%\etc\system\local\outputs.conf

[tcpout]
defaultGroup = default-autolb-group

[tcpout:default-autolb-group]
server = 192.168.1.125:9997

[tcpout-server://192.168.1.125:9997]

# Verified with:
#   splunk list forward-server
#
# Expected output once connected:
#   Active forwards:
#           192.168.1.125:9997
